name: parabeac_core
description: A starting point for Dart libraries or applications.
version: 2.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.2.0
  archive: ^3.1.2
  json_serializable: ^6.0.0
  build_runner: ^2.4.9
  mockito: ^5.0.0
  hex: ^0.2.0
  build: ^2.4.1
  logger: ^2.2.0
  uuid: ^4.4.0
  quick_log: ^5.4.1
  sentry: ^7.19.0
  http2: ^2.3.0
  recase: ^4.1.0
  tuple: ^2.0.2
  path: ^1.6.0
  file: ^7.0.0
  # pbdl:
  #   path: ./pbdl
  directed_graph: ^0.4.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_config: ^1.1.1
# dependency_overrides:
#   analyzer: '0.39.14'
